#+TITLE: CodeLab I, Workshop 20
#+HTML:<br>

* Javascript Game Challenge

** Magic 8-Ball

Magic 8-balls are toys that are designed to help people make decisions. You ask a question, shake the ball, and it gives you a positive or negative answer.

Create a web page with an image of a magic 8-ball and a button that says something like "shake me". When you click on the button, some text should appear with positive, negative, or vague phrases such as: "it looks doubtful", "it appears certain", "the outcome is unclear" or "shake again to find out".

This should involve the simple creation of an array, and the random selection of an element from it. The code below

#+BEGIN_SRC js
// a javascript array:
var myArray = ["apples", "oranges", "pears", "apricots"];

// generate a random number between 0 and the array length
var rand = Math.floor((Math.random() * myArray.length));

// print a random number
console.log(myArray[rand]);
#+END_SRC

** Rock, Paper, Scissors

Create a game of "rock, paper, scissors" in Javascript. There should be three buttons or images on the page: "rock", "paper", and "scissors". The player clicks on one, and the computer randomly chooses a response. The winner is then determined through these rules:

- rock beats scissors
- scissors beats paper
- paper beats rock

For added fun, try implementing a "best 2 of 3" or "best 3 of 5" mode.

** Snap
Make a game with some number of tiles (maybe 25) that you click to turn over. When two are turned over, the game checks to see if they match. If they do, the tiles stay turned over or turn a different colour. Once all tiles are turned over, the game is won.

The tiles could be ~<td>~ elements in a table, coloured with CSS, that contain images when clicked. Or you could use a separate image for the back of the cards.

You should implement a counter to count how many clicks it takes the player to solve the game.

It would be useful to use a "for" loop in Javascript for this game. Here's a basic example:

#+BEGIN_SRC js
// here's our array again
var myArray = ["apples", "oranges", "pears", "apricots"];

// this "for" loop goes through the array and prints each one to the console
for (var i = 0; i < myArray.length; i++) {
  console.log(myArray[i]);
}
#+END_SRC

** Tic-tac-toe

Implement a game of "tic-tac-toe" (otherwise known as "noughts and crosses"). The rules are described [[https://en.wikipedia.org/wiki/Tic-tac-toe][here]].

The simplest way to do this is to create a table of square ~<td>~ elements that fill alternately with "O" and "X" when clicked. The tricky part is working out when a winning combination has been played, though. Good luck!
