#+TITLE:The Javascript Widget Challenge
#+HTML:<br>

Today's task is to use Javascript to add some "widgets" to your Bath Spa Facebook clone. This will actually make it more like MySpace than Facebook!

Here are some ideas for widgets / features you can add:

* Easy

** Magic 8-Ball
This widget should have an image of an 8-ball in the middle. When you click on it, it says something mysterious like "It looks doubtful" or "The outlook is good".

** Random Status Generator
Add an extra button next to the status update text box that says something like "whatever". When you click on it, it will randomly select a status such as "Feeling random today! YOLO!".

** Emoji Bar
Have a bunch of emojis below the status update text box. If you click on one, it sets that as your status.

* Tricky
** Image Carousel
Have a selection of "cover" / background images that change after a certain amount of time. You may need to look into how to use timers in Javascript. Bonus points if you can animate the transitions! Look into CSS transitions for a simple way to do this.

** Calculator
Remember how we made a calculator in PHP? And it turned out kinda... not great? Well, now's your chance to fix that! It's much easier to make one in Javascript.

** Clock Widget
Create a digital (or analogue if you're feeling really ambitious) clock to display the time and date somewhere on your profile page.

** Tic-tac-toe game
Add a simple game of noughts-and-crosses to your website. You can do this using simple clickable div elements, or buttons styled with CSS.

* Challenging

** Music Player
Using this [[./multimedia.html][Audio API guide]], embed some MP3 songs into your site and add some controls to create a basic MP3 player.

** Weather Widget
Using a weather API such as [[https://developer.yahoo.com/weather][Yahoo! Weather]] or [[http://wttr.in][wttr.in]], display an icon and information for today's weather.

** Location Widget
Use Javascript's location service API to check the user's location and display it on the page. If you want an extra challenge, you can use the user's location to update the weather widget.

** A way to add/remove widgets to the site
Include a way to add (using a menu) or remove widgets to your page.

